# -*- coding: utf-8 -*-
"""Cross_validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vERjyFmPb4WwPjKEjofKP2aUnh59xZ1
"""

!pip install faiss-gpu
!pip install rank_bm25
!pip install sentence_transformers

import pandas as pd
import numpy as np
import faiss

from tqdm import tqdm
from collections import Counter

from sentence_transformers import SentenceTransformer
from rank_bm25 import BM25Okapi

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    classification_report
)

df = pd.read_csv(
    "/content/MASTER_FINANCIAL_CORPUS_V1.csv"
)

print("Dataset:",df.shape)


model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)


all_embeddings = model.encode(
    df["Title"].astype(str).tolist(),
    normalize_embeddings=True,
    show_progress_bar=True
).astype("float32")

print("Embeddings:",all_embeddings.shape)


# 5 FOLD CV


skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

fold_scores=[]

for fold,(train_idx,test_idx) in enumerate(
    skf.split(
        df["Title"],
        df["FinBERT_Label"]
    )
):

    print("\n"+"="*50)
    print(f"FOLD {fold+1}")
    print("="*50)

    train_df = df.iloc[train_idx].reset_index(drop=True)
    test_df = df.iloc[test_idx].reset_index(drop=True)

    train_embeddings = all_embeddings[train_idx]
    test_embeddings = all_embeddings[test_idx]


    # FAISS INDEX


    index = faiss.IndexFlatIP(
        train_embeddings.shape[1]
    )

    index.add(train_embeddings)

    print("Vectors Stored:",index.ntotal)

    # BM25


    tokenized_corpus = [
        text.lower().split()
        for text in train_df["Title"].astype(str)
    ]

    bm25 = BM25Okapi(
        tokenized_corpus
    )


    # HYBRID RETRIEVAL

    def bm25andfaiss(
        query,
        query_embedding,
        k=5
    ):

        bm25_scores = bm25.get_scores(
            query.lower().split()
        )

        top_bm_idx = np.argsort(
            bm25_scores
        )[::-1][:k]

        D,I = index.search(
            query_embedding.reshape(1,-1),
            k
        )

        top_faiss_idx = I[0]

        combined_idx = list(
            set(top_bm_idx.tolist())
            |
            set(top_faiss_idx.tolist())
        )

        return combined_idx


    # PREDICTION


    def hybrid_predict(
        query,
        query_embedding,
        k=5
    ):

        docs = bm25andfaiss(
            query,
            query_embedding,
            k
        )

        labels = train_df.iloc[
            docs
        ]["FinBERT_Label"].tolist()

        return Counter(
            labels
        ).most_common(1)[0][0]


    # EVALUATION


    y_true = test_df[
        "FinBERT_Label"
    ].tolist()

    y_pred=[]

    for i,query in enumerate(
        tqdm(test_df["Title"])
    ):

        pred = hybrid_predict(
            query,
            test_embeddings[i],
            k=5
        )

        y_pred.append(pred)

    acc = accuracy_score(
        y_true,
        y_pred
    )

    fold_scores.append(acc)

    print(
        f"Fold Accuracy: {acc:.4f}"
    )

    print(
        classification_report(
            y_true,
            y_pred
        )
    )
# FINAL RESULTS

print("5 FOLD CROSS VALIDATION")

for i,score in enumerate(fold_scores):
    print(
        f"Fold {i+1}: {score:.4f}"
    )

print(
    f"\nMean Accuracy: {np.mean(fold_scores):.4f}"
)

print(
    f"Std Dev: {np.std(fold_scores):.4f}"
)