# -*- coding: utf-8 -*-
"""FAISS+BM25+RRF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120v3Q2j8xvibPaZw2ARqT8BLlcDcC5PM
"""

!pip install rank-bm25
!pip install faiss-cpu

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import faiss

from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
from collections import Counter

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

train_df = pd.read_csv(
    "/content/drive/MyDrive/Research/train_df.csv"
)
test_df = pd.read_csv(
    "/content/drive/MyDrive/Research/test_df.csv"
)
model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)
train_embeddings = np.load(
    "/content/drive/MyDrive/Research/train_embeddings.npy"
)

print("Embeddings:", train_embeddings.shape)
index = faiss.read_index(
    "/content/drive/MyDrive/Research/faiss_index.bin"
)

print("Vectors Stored:", index.ntotal)

tokenized_corpus = [
    text.lower().split()
    for text in train_df["Title"].astype(str)
]

bm25 = BM25Okapi(
    tokenized_corpus
)

print("BM25 Ready")

import numpy as np
import faiss
from rank_bm25 import BM25Okapi
def bm25andfaiss(query,k=5):
  bm25_scores=bm25.get_scores(query.lower().split())
  top_bm_idx=np.argsort(bm25_scores)[::-1][:k]

  q_vec=model.encode([query],normalize_embeddings=True).astype('float32')
  D,I=index.search(q_vec,k)
  top_faiss_idx=I[0]
  combined_idx=list(set(top_bm_idx.tolist()) | set(top_faiss_idx.tolist()))
  return combined_idx

def hybrid_predict(query,k=5):

    docs = bm25andfaiss(
        query,
        k
    )

    labels = (
        train_df.iloc[docs]
        ["FinBERT_Label"]
        .tolist()
    )

    prediction = Counter(
        labels
    ).most_common(1)[0][0]

    return prediction

y_true = test_df[
    "FinBERT_Label"
].tolist()

from tqdm import tqdm

y_pred=[]

for query in tqdm(test_df["Title"]):

    pred=hybrid_predict(
        query,
        k=5
    )

    y_pred.append(pred)

acc=accuracy_score(y_true,y_pred)
print(f"Accuracy:{acc:.4f}")
print("\n Classification_Report:\n")
print(classification_report(y_true,y_pred))
print("\n Confusion_Matrix:\n")
print(confusion_matrix(y_true,y_pred))

def bm25_and_faiss_and_RRF(query,k=5,fetch_k=50,rrf_k=60):
  bm25_scores=bm25.get_scores(query.lower().split())
  top_bm_idx=np.argsort(bm25_scores)[::-1][:fetch_k]

  q_vec=model.encode([query],normalize_embeddings=True).astype('float32')
  D,I=index.search(q_vec,fetch_k)
  top_faiss_idx=I[0]
  scores={}
  for rank,doc_id in enumerate(top_bm_idx):
    scores[doc_id]=scores.get(doc_id,0.0)+1.0/(rrf_k+rank+1)

  for rank,doc_id in enumerate(top_faiss_idx):
    scores[doc_id]=scores.get(doc_id,0.0)+1.0/(rrf_k+rank+1)

  sorted_docs=sorted(scores.items(),key=lambda x:x[1],reverse=True)
  return [doc_id for doc_id,_ in sorted_docs[:k]]

from collections import Counter
def rrf_predict(query,k=5):
  docs=bm25_and_faiss_and_RRF(query,k=5)
  labels=train_df.iloc[docs]['FinBERT_Label'].tolist()
  prediction=Counter(labels).most_common(1)[0][0]
  return prediction

query=test_df.iloc[0]['Title']
print(query)
print(rrf_predict(query,k=5))
print(test_df.iloc[0]["FinBERT_Label"])

from tqdm import tqdm
y_true=test_df['FinBERT_Label'].tolist()
y_pred=[]
for query in tqdm(test_df['Title']):
  pred=rrf_predict(query,k=5)
  y_pred.append(pred)

acc=accuracy_score(y_true,y_pred)
print(f"Accuracy:{acc:.4f}")
print("\n Classification_Report:\n")
print(classification_report(y_true,y_pred))
print("\n Confusion_Matrix:\n")
print(confusion_matrix(y_true,y_pred))