# -*- coding: utf-8 -*-
"""FAISS_ONLY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YlrOYIWNfwH8Snz2s1W-JfW4OQ-s1fh9
"""

!pip install sentence-transformers faiss-cpu pandas numpy scikit-learn

import pandas as pd
df = pd.read_csv(
    "MASTER_FINANCIAL_CORPUS_V1.csv"
)
print(df.shape)
df.head()

from sentence_transformers import SentenceTransformer
model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)
embeddings = model.encode(
    df["Title"].tolist(),
    batch_size=64,
    show_progress_bar=True
)

print(embeddings.shape)

import faiss
import numpy as np
embeddings = np.array(
    embeddings,
    dtype=np.float32
)
faiss.normalize_L2(
    embeddings
)
index = faiss.IndexFlatIP(
    embeddings.shape[1]
)
index.add(
    embeddings
)
print(
    index.ntotal
)

query = "Infosys divident"

query_embedding = model.encode(
    [query]
)

query_embedding = np.array(
    query_embedding,
    dtype=np.float32
)

faiss.normalize_L2(
    query_embedding
)

D, I = index.search(
    query_embedding,
    5
)

for idx in I[0]:
    print(
        df.iloc[idx]["Title"]
    )
    print(
        df.iloc[idx]["FinBERT_Label"]
    )
    print()

import pandas as pd
import numpy as np
import faiss

from sentence_transformers import SentenceTransformer

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)
df = pd.read_csv("/content/MASTER_FINANCIAL_CORPUS_V1.csv")
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df["FinBERT_Label"],
    random_state=42
)

print("Train:", train_df.shape)
print("Test :", test_df.shape)
model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)
train_embeddings = model.encode(
    train_df["Title"].tolist(),
    batch_size=64,
    show_progress_bar=True
)

train_embeddings = np.array(
    train_embeddings,
    dtype=np.float32
)

faiss.normalize_L2(train_embeddings)
index = faiss.IndexFlatIP(
    train_embeddings.shape[1]
)

index.add(train_embeddings)

print("Vectors Stored:", index.ntotal)
test_embeddings = model.encode(
    test_df["Title"].tolist(),
    batch_size=64,
    show_progress_bar=True
)

test_embeddings = np.array(
    test_embeddings,
    dtype=np.float32
)

faiss.normalize_L2(test_embeddings)
K = 5

D, I = index.search(
    test_embeddings,
    K
)
train_labels = train_df["FinBERT_Label"].tolist()

predictions = []

for neighbors in I:

    labels = [
        train_labels[idx]
        for idx in neighbors
    ]

    prediction = max(
        set(labels),
        key=labels.count
    )

    predictions.append(prediction)

y_true = test_df["FinBERT_Label"].tolist()

acc = accuracy_score(
    y_true,
    predictions
)

print("FAISS BASELINE")

print(f"Accuracy: {acc:.4f}")

print("\nClassification Report:\n")

print(
    classification_report(
        y_true,
        predictions
    )
)

print("\nConfusion Matrix:\n")

print(
    confusion_matrix(
        y_true,
        predictions
    )
)