# -*- coding: utf-8 -*-
"""Faiss+bm25+rrf_cross_validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aneXCUjXuEjCliUj1LA8bh9vv4lVCldt
"""

!pip install rank_bm25
!pip install faiss-cpu

import pandas as pd
import numpy as np
import faiss

from tqdm import tqdm
from collections import Counter

from sentence_transformers import SentenceTransformer
from rank_bm25 import BM25Okapi

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score,classification_report

df=pd.read_csv("/content/MASTER_FINANCIAL_CORPUS_V1.csv")

print("Dataset:",df.shape)

model=SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

all_embeddings=model.encode(
    df["Title"].astype(str).tolist(),
    normalize_embeddings=True,
    show_progress_bar=True
).astype("float32")

print("Embeddings:",all_embeddings.shape)

# 5 FOLD CV

skf=StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

fold_scores=[]

for fold,(train_idx,test_idx) in enumerate(skf.split(df["Title"],df["FinBERT_Label"])):

    print("\n"+"="*50)
    print(f"FOLD {fold+1}")
    print("="*50)

    train_df=df.iloc[train_idx].reset_index(drop=True)
    test_df=df.iloc[test_idx].reset_index(drop=True)

    train_embeddings=all_embeddings[train_idx]
    test_embeddings=all_embeddings[test_idx]

    # FAISS INDEX

    index=faiss.IndexFlatIP(train_embeddings.shape[1])

    index.add(train_embeddings)

    print("Vectors Stored:",index.ntotal)

    # BM25

    tokenized_corpus=[text.lower().split() for text in train_df["Title"].astype(str)]

    bm25=BM25Okapi(tokenized_corpus)

    # HYBRID RETRIEVAL

    def bm25_and_faiss_and_RRF(query,query_embedding,k=5,fetch_k=50,rrf_k=60):

        bm25_scores=bm25.get_scores(query.lower().split())

        top_bm_idx=np.argsort(bm25_scores)[::-1][:fetch_k]

        D,I=index.search(query_embedding.reshape(1,-1),fetch_k)

        top_faiss_idx=I[0]

        scores={}

        for rank,doc_id in enumerate(top_bm_idx):
            scores[doc_id]=scores.get(doc_id,0.0)+1.0/(rrf_k+rank+1)

        for rank,doc_id in enumerate(top_faiss_idx):
            scores[doc_id]=scores.get(doc_id,0.0)+1.0/(rrf_k+rank+1)

        sorted_docs=sorted(scores.items(),key=lambda x:x[1],reverse=True)

        return [doc_id for doc_id,_ in sorted_docs[:k]]

    def hybrid_predict(query,query_embedding,k=5):

        retrieved_docs=bm25_and_faiss_and_RRF(
            query,
            query_embedding,
            k=k
        )

        labels=train_df.iloc[retrieved_docs]["FinBERT_Label"].tolist()

        return Counter(labels).most_common(1)[0][0]

    # EVALUATION

    y_true=test_df["FinBERT_Label"].tolist()

    y_pred=[]

    for i,query in enumerate(tqdm(test_df["Title"])):

        pred=hybrid_predict(query,test_embeddings[i],k=5)

        y_pred.append(pred)

    acc=accuracy_score(y_true,y_pred)

    fold_scores.append(acc)

    print(f"Fold Accuracy: {acc:.4f}")

    print(classification_report(y_true,y_pred))

# FINAL RESULTS

print("5 FOLD CROSS VALIDATION")

for i,score in enumerate(fold_scores):
    print(f"Fold {i+1}: {score:.4f}")

print(f"\nMean Accuracy: {np.mean(fold_scores):.4f}")

print(f"Std Dev: {np.std(fold_scores):.4f}")